// ─── Supported languages ────────────────────────────────────────────────────

export interface LanguageConfig {
  code: string;
  name: string;          // display name in French
  nativeName: string;    // name in the language itself
  flag: string;          // emoji flag
  rtl: boolean;          // right-to-left script
  script: string;        // writing system name
  ttsLang: string;       // BCP-47 tag for expo-speech
  alphabet: AlphabetLetter[];
  categories: VocabCategory[];
  greetingWord: string;  // e.g. "مرحباً" shown on HomeScreen
  familiarName: string;  // "Arabe", "Japonais", etc.
  difficulty: 'easy' | 'medium' | 'hard'; // for UI hint
  aiSeedPrompt: string;  // base instruction for AI (language-specific)
}

export interface AlphabetLetter {
  letter: string;
  name: string;
  sound: string;
  example?: string;
  // optional positional forms (Arabic only)
  isolated?: string;
  initial?: string;
  medial?: string;
  final?: string;
  tips?: string;
}

export interface VocabCategory {
  id: string;
  label: string;         // French label
  emoji: string;
  nativeLabel?: string;  // label in the target language
}

// ─── Arabic ─────────────────────────────────────────────────────────────────

const ARABIC_ALPHABET: AlphabetLetter[] = [
  { letter: 'ا', name: 'Alif',  sound: 'a',  isolated: 'ا', initial: 'ا',   medial: 'ـا',  final: 'ـا',  example: 'أب (ab - père)',         tips: 'Trait vertical, légèrement incliné.' },
  { letter: 'ب', name: 'Ba',    sound: 'b',  isolated: 'ب', initial: 'بـ',  medial: 'ـبـ', final: 'ـب',  example: 'باب (bab - porte)',        tips: 'Ligne horizontale, point dessous.' },
  { letter: 'ت', name: 'Ta',    sound: 't',  isolated: 'ت', initial: 'تـ',  medial: 'ـتـ', final: 'ـت',  example: 'تين (tīn - figue)',        tips: 'Comme Ba, deux points au-dessus.' },
  { letter: 'ث', name: 'Tha',   sound: 'th', isolated: 'ث', initial: 'ثـ',  medial: 'ـثـ', final: 'ـث',  example: 'ثعلب (renard)',           tips: 'Comme Ba, trois points au-dessus.' },
  { letter: 'ج', name: 'Jim',   sound: 'j',  isolated: 'ج', initial: 'جـ',  medial: 'ـجـ', final: 'ـج',  example: 'جمل (chameau)',           tips: 'Courbe crochet vers le bas.' },
  { letter: 'ح', name: 'Ha',    sound: 'ḥ',  isolated: 'ح', initial: 'حـ',  medial: 'ـحـ', final: 'ـح',  example: 'حصان (cheval)',           tips: 'Deux courbes jointes, sans point.' },
  { letter: 'خ', name: 'Kha',   sound: 'kh', isolated: 'خ', initial: 'خـ',  medial: 'ـخـ', final: 'ـخ',  example: 'خبز (pain)',              tips: 'Comme Ha, point au-dessus.' },
  { letter: 'د', name: 'Dal',   sound: 'd',  isolated: 'د', initial: 'د',   medial: 'ـد',  final: 'ـد',  example: 'دجاجة (poule)',          tips: 'Angle droit, ne se connecte pas à gauche.' },
  { letter: 'ذ', name: 'Dhal',  sound: 'dh', isolated: 'ذ', initial: 'ذ',   medial: 'ـذ',  final: 'ـذ',  example: 'ذهب (or)',                tips: 'Comme Dal, point au-dessus.' },
  { letter: 'ر', name: 'Ra',    sound: 'r',  isolated: 'ر', initial: 'ر',   medial: 'ـر',  final: 'ـر',  example: 'رأس (tête)',              tips: 'Petite courbe vers le bas-droite.' },
  { letter: 'ز', name: 'Zay',   sound: 'z',  isolated: 'ز', initial: 'ز',   medial: 'ـز',  final: 'ـز',  example: 'زهرة (fleur)',            tips: 'Comme Ra, point au-dessus.' },
  { letter: 'س', name: 'Sin',   sound: 's',  isolated: 'س', initial: 'سـ',  medial: 'ـسـ', final: 'ـس',  example: 'سمك (poisson)',           tips: 'Trois dents puis queue.' },
  { letter: 'ش', name: 'Shin',  sound: 'sh', isolated: 'ش', initial: 'شـ',  medial: 'ـشـ', final: 'ـش',  example: 'شمس (soleil)',            tips: 'Comme Sin, trois points au-dessus.' },
  { letter: 'ص', name: 'Sad',   sound: 'ṣ',  isolated: 'ص', initial: 'صـ',  medial: 'ـصـ', final: 'ـص',  example: 'صقر (faucon)',            tips: 'Ovale fermé avec queue vers le bas.' },
  { letter: 'ض', name: 'Dad',   sound: 'ḍ',  isolated: 'ض', initial: 'ضـ',  medial: 'ـضـ', final: 'ـض',  example: 'ضفدع (grenouille)',       tips: 'Comme Sad, point au-dessus.' },
  { letter: 'ط', name: 'Tah',   sound: 'ṭ',  isolated: 'ط', initial: 'طـ',  medial: 'ـطـ', final: 'ـط',  example: 'طائر (oiseau)',           tips: 'Cercle avec trait vertical.' },
  { letter: 'ظ', name: 'Dhah',  sound: 'ẓ',  isolated: 'ظ', initial: 'ظـ',  medial: 'ـظـ', final: 'ـظ',  example: 'ظفر (ongle)',             tips: 'Comme Tah, point au-dessus.' },
  { letter: 'ع', name: 'Ayn',   sound: "'",  isolated: 'ع', initial: 'عـ',  medial: 'ـعـ', final: 'ـع',  example: 'عين (œil)',               tips: 'Spirale ouverte.' },
  { letter: 'غ', name: 'Ghayn', sound: 'gh', isolated: 'غ', initial: 'غـ',  medial: 'ـغـ', final: 'ـغ',  example: 'غراب (corbeau)',          tips: 'Comme Ayn, point au-dessus.' },
  { letter: 'ف', name: 'Fa',    sound: 'f',  isolated: 'ف', initial: 'فـ',  medial: 'ـفـ', final: 'ـف',  example: 'فيل (éléphant)',          tips: 'Cercle, queue, point au-dessus.' },
  { letter: 'ق', name: 'Qaf',   sound: 'q',  isolated: 'ق', initial: 'قـ',  medial: 'ـقـ', final: 'ـق',  example: 'قمر (lune)',              tips: 'Cercle plus profond, deux points.' },
  { letter: 'ك', name: 'Kaf',   sound: 'k',  isolated: 'ك', initial: 'كـ',  medial: 'ـكـ', final: 'ـك',  example: 'كتاب (livre)',            tips: 'Comme un L avec une tête.' },
  { letter: 'ل', name: 'Lam',   sound: 'l',  isolated: 'ل', initial: 'لـ',  medial: 'ـلـ', final: 'ـل',  example: 'ليمون (citron)',          tips: 'Courbe descendante, boucle à gauche.' },
  { letter: 'م', name: 'Mim',   sound: 'm',  isolated: 'م', initial: 'مـ',  medial: 'ـمـ', final: 'ـم',  example: 'ماء (eau)',               tips: 'Petit cercle, queue descendante.' },
  { letter: 'ن', name: 'Nun',   sound: 'n',  isolated: 'ن', initial: 'نـ',  medial: 'ـنـ', final: 'ـن',  example: 'نجم (étoile)',            tips: 'Demi-cercle ouvert, point au-dessus.' },
  { letter: 'ه', name: 'Ha',    sound: 'h',  isolated: 'ه', initial: 'هـ',  medial: 'ـهـ', final: 'ـه',  example: 'هلال (croissant)',        tips: 'Deux cercles imbriqués.' },
  { letter: 'و', name: 'Waw',   sound: 'w',  isolated: 'و', initial: 'و',   medial: 'ـو',  final: 'ـو',  example: 'ورد (rose)',              tips: 'Petit cercle, queue vers le bas.' },
  { letter: 'ي', name: 'Ya',    sound: 'y',  isolated: 'ي', initial: 'يـ',  medial: 'ـيـ', final: 'ـي',  example: 'يد (main)',               tips: 'Courbe, deux points en dessous.' },
];

// ─── Spanish alphabet (common letters with pronunciation) ────────────────────

const SPANISH_ALPHABET: AlphabetLetter[] = [
  { letter: 'A', name: 'A',   sound: 'a',  example: 'agua (eau)'        },
  { letter: 'B', name: 'Be',  sound: 'b',  example: 'barco (bateau)'    },
  { letter: 'C', name: 'Ce',  sound: 'k/θ',example: 'casa (maison)'     },
  { letter: 'CH',name: 'Che', sound: 'tʃ', example: 'chocolate'         },
  { letter: 'D', name: 'De',  sound: 'd',  example: 'día (jour)'        },
  { letter: 'E', name: 'E',   sound: 'e',  example: 'estrella (étoile)' },
  { letter: 'F', name: 'Efe', sound: 'f',  example: 'flor (fleur)'      },
  { letter: 'G', name: 'Ge',  sound: 'g/x',example: 'gato (chat)'      },
  { letter: 'H', name: 'Hache',sound: '-', example: 'hora (heure)'      },
  { letter: 'I', name: 'I',   sound: 'i',  example: 'isla (île)'        },
  { letter: 'J', name: 'Jota',sound: 'x',  example: 'jardín (jardin)'   },
  { letter: 'L', name: 'Ele', sound: 'l',  example: 'luna (lune)'       },
  { letter: 'LL',name: 'Elle',sound: 'ʝ',  example: 'llave (clé)'       },
  { letter: 'M', name: 'Eme', sound: 'm',  example: 'mar (mer)'         },
  { letter: 'N', name: 'Ene', sound: 'n',  example: 'noche (nuit)'      },
  { letter: 'Ñ', name: 'Eñe', sound: 'ɲ',  example: 'niño (enfant)'     },
  { letter: 'O', name: 'O',   sound: 'o',  example: 'oso (ours)'        },
  { letter: 'P', name: 'Pe',  sound: 'p',  example: 'pan (pain)'        },
  { letter: 'Q', name: 'Cu',  sound: 'k',  example: 'queso (fromage)'   },
  { letter: 'R', name: 'Erre',sound: 'r',  example: 'rosa (rose)'       },
  { letter: 'RR',name: 'Doble erre',sound: 'r̄', example: 'perro (chien)' },
  { letter: 'S', name: 'Ese', sound: 's',  example: 'sol (soleil)'      },
  { letter: 'T', name: 'Te',  sound: 't',  example: 'tiempo (temps)'    },
  { letter: 'U', name: 'U',   sound: 'u',  example: 'uva (raisin)'      },
  { letter: 'V', name: 'Uve', sound: 'b',  example: 'vino (vin)'        },
  { letter: 'X', name: 'Equis',sound: 'ks',example: 'examen'            },
  { letter: 'Y', name: 'I griega',sound: 'ʝ',example: 'yo (je)'         },
  { letter: 'Z', name: 'Zeta',sound: 'θ',  example: 'zapato (chaussure)'},
];

// ─── Mandarin tones / initials (simplified) ──────────────────────────────────

const MANDARIN_ALPHABET: AlphabetLetter[] = [
  { letter: 'b', name: 'b (bo)',  sound: 'b',  example: '爸 bà (père)'    },
  { letter: 'p', name: 'p (po)',  sound: 'p',  example: '朋 péng (ami)'   },
  { letter: 'm', name: 'm (mo)',  sound: 'm',  example: '妈 mā (mère)'    },
  { letter: 'f', name: 'f (fo)',  sound: 'f',  example: '飞 fēi (voler)'  },
  { letter: 'd', name: 'd (de)',  sound: 'd',  example: '大 dà (grand)'   },
  { letter: 't', name: 't (te)',  sound: 't',  example: '天 tiān (ciel)'  },
  { letter: 'n', name: 'n (ne)',  sound: 'n',  example: '你 nǐ (toi)'     },
  { letter: 'l', name: 'l (le)',  sound: 'l',  example: '来 lái (venir)'  },
  { letter: 'g', name: 'g (ge)',  sound: 'g',  example: '国 guó (pays)'   },
  { letter: 'k', name: 'k (ke)',  sound: 'k',  example: '看 kàn (voir)'   },
  { letter: 'h', name: 'h (he)',  sound: 'h',  example: '好 hǎo (bien)'   },
  { letter: 'zh',name: 'zh',      sound: 'ʈʂ', example: '中 zhōng (milieu)'},
  { letter: 'ch',name: 'ch',      sound: 'ʈʂʰ',example: '吃 chī (manger)' },
  { letter: 'sh',name: 'sh',      sound: 'ʂ',  example: '是 shì (être)'   },
  { letter: 'r', name: 'r',       sound: 'ɻ',  example: '人 rén (personne)'},
  { letter: 'ā', name: 'Ton 1 ā', sound: 'ā',  example: 'Ton haut et stable' },
  { letter: 'á', name: 'Ton 2 á', sound: 'á',  example: 'Ton montant'         },
  { letter: 'ǎ', name: 'Ton 3 ǎ', sound: 'ǎ',  example: 'Ton descendant-montant' },
  { letter: 'à', name: 'Ton 4 à', sound: 'à',  example: 'Ton descendant'      },
];

// ─── Japanese hiragana (main 46) ─────────────────────────────────────────────

const JAPANESE_ALPHABET: AlphabetLetter[] = [
  { letter: 'あ', name: 'a',  sound: 'a',  example: '朝 asa (matin)'    },
  { letter: 'い', name: 'i',  sound: 'i',  example: '犬 inu (chien)'    },
  { letter: 'う', name: 'u',  sound: 'u',  example: '海 umi (mer)'      },
  { letter: 'え', name: 'e',  sound: 'e',  example: '駅 eki (gare)'     },
  { letter: 'お', name: 'o',  sound: 'o',  example: '男 otoko (homme)'  },
  { letter: 'か', name: 'ka', sound: 'ka', example: '花 hana / ka (feu)'},
  { letter: 'き', name: 'ki', sound: 'ki', example: '木 ki (arbre)'     },
  { letter: 'く', name: 'ku', sound: 'ku', example: '国 kuni (pays)'    },
  { letter: 'け', name: 'ke', sound: 'ke', example: '家 ke / ie (maison)'},
  { letter: 'こ', name: 'ko', sound: 'ko', example: '子 ko (enfant)'    },
  { letter: 'さ', name: 'sa', sound: 'sa', example: '魚 sakana (poisson)'},
  { letter: 'し', name: 'shi',sound: 'ʃi', example: '塩 shio (sel)'     },
  { letter: 'す', name: 'su', sound: 'su', example: '空 sora (ciel)'    },
  { letter: 'せ', name: 'se', sound: 'se', example: '先生 sensei (prof)' },
  { letter: 'そ', name: 'so', sound: 'so', example: 'そこ soko (là-bas)' },
  { letter: 'た', name: 'ta', sound: 'ta', example: '食べる taberu (manger)'},
  { letter: 'ち', name: 'chi',sound: 'tʃi',example: '地図 chizu (carte)' },
  { letter: 'つ', name: 'tsu',sound: 'tsu',example: '月 tsuki (lune)'   },
  { letter: 'て', name: 'te', sound: 'te', example: '手 te (main)'      },
  { letter: 'と', name: 'to', sound: 'to', example: '時計 tokei (horloge)'},
  { letter: 'な', name: 'na', sound: 'na', example: '名前 namae (prénom)'},
  { letter: 'に', name: 'ni', sound: 'ni', example: '日本 nihon (Japon)' },
  { letter: 'ぬ', name: 'nu', sound: 'nu', example: '犬 inu / nu'       },
  { letter: 'ね', name: 'ne', sound: 'ne', example: '猫 neko (chat)'    },
  { letter: 'の', name: 'no', sound: 'no', example: 'の (particule de)' },
  { letter: 'は', name: 'ha', sound: 'ha', example: '花 hana (fleur)'   },
  { letter: 'ひ', name: 'hi', sound: 'çi', example: '左 hidari (gauche)'},
  { letter: 'ふ', name: 'fu', sound: 'ɸu', example: '冬 fuyu (hiver)'   },
  { letter: 'へ', name: 'he', sound: 'he', example: '部屋 heya (pièce)' },
  { letter: 'ほ', name: 'ho', sound: 'ho', example: '本 hon (livre)'    },
  { letter: 'ま', name: 'ma', sound: 'ma', example: '水 mizu (eau)'     },
  { letter: 'み', name: 'mi', sound: 'mi', example: '耳 mimi (oreille)' },
  { letter: 'む', name: 'mu', sound: 'mu', example: '虫 mushi (insecte)'},
  { letter: 'め', name: 'me', sound: 'me', example: '目 me (œil)'       },
  { letter: 'も', name: 'mo', sound: 'mo', example: 'もっと motto (plus)'},
  { letter: 'や', name: 'ya', sound: 'ja', example: '山 yama (montagne)'},
  { letter: 'ゆ', name: 'yu', sound: 'ju', example: '夢 yume (rêve)'    },
  { letter: 'よ', name: 'yo', sound: 'jo', example: '夜 yoru (nuit)'    },
  { letter: 'ら', name: 'ra', sound: 'ɾa', example: '来年 rainen (l\'an prochain)'},
  { letter: 'り', name: 'ri', sound: 'ɾi', example: '利用 riyou (usage)'},
  { letter: 'る', name: 'ru', sound: 'ɾu', example: '留学 ryugaku (études à l\'étranger)'},
  { letter: 'れ', name: 're', sound: 'ɾe', example: '歴史 rekishi (histoire)'},
  { letter: 'ろ', name: 'ro', sound: 'ɾo', example: '廊下 rōka (couloir)'},
  { letter: 'わ', name: 'wa', sound: 'wa', example: '私 watashi (je)'   },
  { letter: 'を', name: 'wo', sound: 'o',  example: 'を (marqueur OD)'  },
  { letter: 'ん', name: 'n',  sound: 'n',  example: 'ん (nasale finale)' },
];

// ─── Common vocab categories per language ────────────────────────────────────

const COMMON_CATEGORIES: VocabCategory[] = [
  { id: 'greetings',  label: 'Salutations',    emoji: '👋' },
  { id: 'numbers',    label: 'Nombres',         emoji: '🔢' },
  { id: 'family',     label: 'Famille',         emoji: '👨‍👩‍👧' },
  { id: 'food',       label: 'Nourriture',      emoji: '🍕' },
  { id: 'travel',     label: 'Voyage',          emoji: '✈️' },
  { id: 'daily_life', label: 'Vie quotidienne', emoji: '☀️' },
  { id: 'colors',     label: 'Couleurs',        emoji: '🎨' },
  { id: 'animals',    label: 'Animaux',         emoji: '🐱' },
  { id: 'body',       label: 'Corps humain',    emoji: '🫀' },
  { id: 'emotions',   label: 'Émotions',        emoji: '😊' },
];

// ─── Language registry ───────────────────────────────────────────────────────

export const SUPPORTED_LANGUAGES: LanguageConfig[] = [
  {
    code: 'ar',
    name: 'Arabe',
    nativeName: 'العربية',
    flag: '🇸🇦',
    rtl: true,
    script: 'Alphabet arabe',
    ttsLang: 'ar-SA',
    alphabet: ARABIC_ALPHABET,
    categories: [
      ...COMMON_CATEGORIES,
      { id: 'religion', label: 'Religion', emoji: '☪️', nativeLabel: 'دين' },
      { id: 'work',     label: 'Travail',  emoji: '💼', nativeLabel: 'عمل' },
    ],
    greetingWord: 'مرحباً',
    familiarName: 'Arabe',
    difficulty: 'hard',
    aiSeedPrompt: `Tu es un professeur d'arabe bienveillant. Toujours écrire l'arabe AVEC les voyelles (harakat/tashkil). Exemple: "مَرْحَباً" jamais "مرحبا". Translitération en français. Adapter au niveau de l'élève.`,
  },
  {
    code: 'es',
    name: 'Espagnol',
    nativeName: 'Español',
    flag: '🇪🇸',
    rtl: false,
    script: 'Alphabet latin',
    ttsLang: 'es-ES',
    alphabet: SPANISH_ALPHABET,
    categories: COMMON_CATEGORIES,
    greetingWord: '¡Hola!',
    familiarName: 'Espagnol',
    difficulty: 'easy',
    aiSeedPrompt: `Tu es un professeur d'espagnol bienveillant. Donne toujours la prononciation et la traduction française. Utilise des exemples concrets et culturels hispaniques.`,
  },
  {
    code: 'zh',
    name: 'Mandarin',
    nativeName: '普通话',
    flag: '🇨🇳',
    rtl: false,
    script: 'Caractères + Pinyin',
    ttsLang: 'zh-CN',
    alphabet: MANDARIN_ALPHABET,
    categories: COMMON_CATEGORIES,
    greetingWord: '你好！',
    familiarName: 'Mandarin',
    difficulty: 'hard',
    aiSeedPrompt: `Tu es un professeur de mandarin bienveillant. Toujours donner: caractère simplifié, pinyin avec tons, et traduction française. Insister sur l'importance des tons.`,
  },
  {
    code: 'ja',
    name: 'Japonais',
    nativeName: '日本語',
    flag: '🇯🇵',
    rtl: false,
    script: 'Hiragana / Katakana / Kanji',
    ttsLang: 'ja-JP',
    alphabet: JAPANESE_ALPHABET,
    categories: COMMON_CATEGORIES,
    greetingWord: 'こんにちは！',
    familiarName: 'Japonais',
    difficulty: 'hard',
    aiSeedPrompt: `Tu es un professeur de japonais bienveillant. Donne toujours: kana/kanji, romaji et traduction française. Précise le niveau de politesse (formel/informel).`,
  },
  {
    code: 'de',
    name: 'Allemand',
    nativeName: 'Deutsch',
    flag: '🇩🇪',
    rtl: false,
    script: 'Alphabet latin',
    ttsLang: 'de-DE',
    alphabet: [
      { letter: 'A/Ä', name: 'A / Ä (Umlaut)', sound: 'a / ɛ', example: 'Auto (voiture) / Äpfel (pommes)' },
      { letter: 'B',   name: 'B',   sound: 'b',   example: 'Buch (livre)'      },
      { letter: 'C',   name: 'C',   sound: 'ts/k',example: 'Computer'          },
      { letter: 'CH',  name: 'CH',  sound: 'x/ç', example: 'Nacht (nuit)'      },
      { letter: 'D',   name: 'D',   sound: 'd',   example: 'Danke (merci)'     },
      { letter: 'E',   name: 'E',   sound: 'e/ə', example: 'Essen (nourriture)'},
      { letter: 'F',   name: 'F',   sound: 'f',   example: 'Freund (ami)'      },
      { letter: 'G',   name: 'G',   sound: 'g',   example: 'Guten Morgen'      },
      { letter: 'H',   name: 'H',   sound: 'h',   example: 'Haus (maison)'     },
      { letter: 'I',   name: 'I',   sound: 'ɪ',   example: 'Ich (je)'          },
      { letter: 'J',   name: 'J',   sound: 'j',   example: 'Ja (oui)'          },
      { letter: 'K',   name: 'K',   sound: 'k',   example: 'Kind (enfant)'     },
      { letter: 'L',   name: 'L',   sound: 'l',   example: 'Liebe (amour)'     },
      { letter: 'M',   name: 'M',   sound: 'm',   example: 'Mutter (mère)'     },
      { letter: 'N',   name: 'N',   sound: 'n',   example: 'Nein (non)'        },
      { letter: 'O/Ö', name: 'O / Ö',sound:'o/ø', example: 'Ohr (oreille) / Öl' },
      { letter: 'P',   name: 'P',   sound: 'p',   example: 'Platz (place)'     },
      { letter: 'R',   name: 'R',   sound: 'ʁ',   example: 'Rot (rouge)'       },
      { letter: 'SCH', name: 'SCH', sound: 'ʃ',   example: 'Schule (école)'    },
      { letter: 'SP/ST',name:'SP/ST',sound:'ʃp/ʃt',example: 'Sprache (langue)' },
      { letter: 'T',   name: 'T',   sound: 't',   example: 'Tag (jour)'        },
      { letter: 'U/Ü', name: 'U / Ü',sound:'u/y', example: 'Uhr (heure) / Über' },
      { letter: 'V',   name: 'V',   sound: 'f',   example: 'Vater (père)'      },
      { letter: 'W',   name: 'W',   sound: 'v',   example: 'Wasser (eau)'      },
      { letter: 'Z',   name: 'Z',   sound: 'ts',  example: 'Zeit (temps)'      },
      { letter: 'ß',   name: 'Eszett',sound: 's', example: 'Straße (rue)'      },
    ],
    categories: COMMON_CATEGORIES,
    greetingWord: 'Hallo!',
    familiarName: 'Allemand',
    difficulty: 'medium',
    aiSeedPrompt: `Tu es un professeur d'allemand bienveillant. Toujours indiquer le genre (der/die/das) des noms. Donner la prononciation phonétique et la traduction française. Insister sur les règles de déclinaison.`,
  },
  {
    code: 'it',
    name: 'Italien',
    nativeName: 'Italiano',
    flag: '🇮🇹',
    rtl: false,
    script: 'Alphabet latin',
    ttsLang: 'it-IT',
    alphabet: [
      { letter: 'A',  name: 'A',    sound: 'a',   example: 'amore (amour)'       },
      { letter: 'B',  name: 'Bi',   sound: 'b',   example: 'bambino (enfant)'    },
      { letter: 'C',  name: 'Ci',   sound: 'k/tʃ',example: 'casa (maison)'       },
      { letter: 'D',  name: 'Di',   sound: 'd',   example: 'donna (femme)'       },
      { letter: 'E',  name: 'E',    sound: 'e',   example: 'estate (été)'        },
      { letter: 'F',  name: 'Effe', sound: 'f',   example: 'fiore (fleur)'       },
      { letter: 'G',  name: 'Gi',   sound: 'g/dʒ',example: 'gatto (chat)'        },
      { letter: 'GH', name: 'GH',   sound: 'g',   example: 'ghiaccio (glace)'    },
      { letter: 'GL', name: 'GL',   sound: 'ʎ',   example: 'figlio (fils)'       },
      { letter: 'GN', name: 'GN',   sound: 'ɲ',   example: 'gnocchi'             },
      { letter: 'H',  name: 'Acca', sound: 'muet',example: 'ho (j\'ai)'          },
      { letter: 'I',  name: 'I',    sound: 'i',   example: 'isola (île)'         },
      { letter: 'L',  name: 'Elle', sound: 'l',   example: 'luna (lune)'         },
      { letter: 'M',  name: 'Emme', sound: 'm',   example: 'mare (mer)'          },
      { letter: 'N',  name: 'Enne', sound: 'n',   example: 'notte (nuit)'        },
      { letter: 'O',  name: 'O',    sound: 'o',   example: 'orso (ours)'         },
      { letter: 'P',  name: 'Pi',   sound: 'p',   example: 'pane (pain)'         },
      { letter: 'QU', name: 'Qu',   sound: 'kw',  example: 'quando (quand)'      },
      { letter: 'R',  name: 'Erre', sound: 'r',   example: 'rosso (rouge)'       },
      { letter: 'SC', name: 'Sc',   sound: 'sk/ʃ',example: 'scuola (école)'      },
      { letter: 'T',  name: 'Ti',   sound: 't',   example: 'tempo (temps)'       },
      { letter: 'U',  name: 'U',    sound: 'u',   example: 'uomo (homme)'        },
      { letter: 'V',  name: 'Vu',   sound: 'v',   example: 'verde (vert)'        },
      { letter: 'Z',  name: 'Zeta', sound: 'ts/dz',example: 'zucchero (sucre)'  },
    ],
    categories: COMMON_CATEGORIES,
    greetingWord: 'Ciao!',
    familiarName: 'Italien',
    difficulty: 'easy',
    aiSeedPrompt: `Tu es un professeur d'italien bienveillant. Toujours donner le genre (masculin/féminin) des noms. Inclure la prononciation et la traduction française. Donner des exemples de la culture italienne.`,
  },
  {
    code: 'pt',
    name: 'Portugais',
    nativeName: 'Português',
    flag: '🇧🇷',
    rtl: false,
    script: 'Alphabet latin',
    ttsLang: 'pt-BR',
    alphabet: [
      { letter: 'A',  name: 'A',   sound: 'a/ɐ', example: 'água (eau)'        },
      { letter: 'Ã',  name: 'Ã',   sound: 'ɐ̃',   example: 'irmã (sœur)'       },
      { letter: 'B',  name: 'Bê',  sound: 'b',   example: 'bom (bon)'         },
      { letter: 'C',  name: 'Cê',  sound: 'k/s', example: 'casa (maison)'     },
      { letter: 'Ç',  name: 'Cê-cedilha',sound: 's', example: 'açúcar (sucre)' },
      { letter: 'CH', name: 'CH',  sound: 'ʃ',   example: 'chave (clé)'       },
      { letter: 'D',  name: 'Dê',  sound: 'd/dʒ',example: 'dia (jour)'        },
      { letter: 'E',  name: 'E',   sound: 'e/ɛ', example: 'escola (école)'    },
      { letter: 'F',  name: 'Efe', sound: 'f',   example: 'flor (fleur)'      },
      { letter: 'LH', name: 'LH',  sound: 'ʎ',   example: 'filho (fils)'      },
      { letter: 'NH', name: 'NH',  sound: 'ɲ',   example: 'amanhã (demain)'   },
      { letter: 'Ó',  name: 'Ó',   sound: 'ɔ',   example: 'óculos (lunettes)' },
      { letter: 'ÃO', name: 'ÃO',  sound: 'ɐ̃w̃',  example: 'irmão (frère)'     },
      { letter: 'R',  name: 'Erre',sound: 'r/x',  example: 'rio (rivière)'     },
    ],
    categories: COMMON_CATEGORIES,
    greetingWord: 'Olá!',
    familiarName: 'Portugais',
    difficulty: 'easy',
    aiSeedPrompt: `Tu es un professeur de portugais (brésilien) bienveillant. Donner la prononciation brésilienne et la traduction française. Inclure des éléments culturels brésiliens et portugais.`,
  },
  {
    code: 'ru',
    name: 'Russe',
    nativeName: 'Русский',
    flag: '🇷🇺',
    rtl: false,
    script: 'Alphabet cyrillique',
    ttsLang: 'ru-RU',
    alphabet: [
      { letter: 'А', name: 'A',   sound: 'a',  example: 'аппетит (appétit)' },
      { letter: 'Б', name: 'Bé',  sound: 'b',  example: 'брат (frère)'      },
      { letter: 'В', name: 'Vé',  sound: 'v',  example: 'вода (eau)'        },
      { letter: 'Г', name: 'Gué', sound: 'g',  example: 'год (année)'       },
      { letter: 'Д', name: 'Dé',  sound: 'd',  example: 'дом (maison)'      },
      { letter: 'Е', name: 'Yé',  sound: 'jɛ', example: 'есть (manger)'     },
      { letter: 'Ё', name: 'Yo',  sound: 'jo', example: 'ёж (hérisson)'     },
      { letter: 'Ж', name: 'Jé',  sound: 'ʒ',  example: 'журнал (journal)'  },
      { letter: 'З', name: 'Zé',  sound: 'z',  example: 'звук (son)'        },
      { letter: 'И', name: 'I',   sound: 'i',  example: 'имя (prénom)'      },
      { letter: 'Й', name: 'I court',sound: 'j',example: 'чай (thé)'        },
      { letter: 'К', name: 'Ka',  sound: 'k',  example: 'книга (livre)'     },
      { letter: 'Л', name: 'Él',  sound: 'l',  example: 'лето (été)'        },
      { letter: 'М', name: 'Em',  sound: 'm',  example: 'мама (maman)'      },
      { letter: 'Н', name: 'En',  sound: 'n',  example: 'нет (non)'         },
      { letter: 'О', name: 'O',   sound: 'o/ɐ',example: 'окно (fenêtre)'    },
      { letter: 'П', name: 'Pé',  sound: 'p',  example: 'папа (papa)'       },
      { letter: 'Р', name: 'Er',  sound: 'r',  example: 'рыба (poisson)'    },
      { letter: 'С', name: 'Es',  sound: 's',  example: 'слово (mot)'       },
      { letter: 'Т', name: 'Té',  sound: 't',  example: 'ты (tu)'           },
      { letter: 'У', name: 'U',   sound: 'u',  example: 'утро (matin)'      },
      { letter: 'Ф', name: 'Ef',  sound: 'f',  example: 'форма (forme)'     },
      { letter: 'Х', name: 'Kha', sound: 'x',  example: 'хлеб (pain)'       },
      { letter: 'Ц', name: 'Tsé', sound: 'ts', example: 'цвет (couleur)'    },
      { letter: 'Ч', name: 'Ché', sound: 'tʃ', example: 'час (heure)'       },
      { letter: 'Ш', name: 'Cha', sound: 'ʃ',  example: 'школа (école)'     },
      { letter: 'Щ', name: 'Chtcha',sound: 'ʃtʃ',example: 'щи (soupe)'    },
      { letter: 'Ъ', name: 'Signe dur',sound: '',example: 'разъезд'         },
      { letter: 'Ы', name: 'Y',   sound: 'ɨ',  example: 'рыба (poisson)'    },
      { letter: 'Ь', name: 'Signe mou',sound: 'ʲ',example: 'день (jour)'   },
      { letter: 'Э', name: 'É',   sound: 'ɛ',  example: 'это (ceci)'        },
      { letter: 'Ю', name: 'You', sound: 'ju', example: 'юг (sud)'          },
      { letter: 'Я', name: 'Ya',  sound: 'ja', example: 'я (je)'            },
    ],
    categories: COMMON_CATEGORIES,
    greetingWord: 'Привет!',
    familiarName: 'Russe',
    difficulty: 'hard',
    aiSeedPrompt: `Tu es un professeur de russe bienveillant. Toujours donner: cyrillique, translittération latine et traduction française. Expliquer les aspects grammaticaux (genre, cas) progressivement.`,
  },
  {
    code: 'ko',
    name: 'Coréen',
    nativeName: '한국어',
    flag: '🇰🇷',
    rtl: false,
    script: 'Hangeul',
    ttsLang: 'ko-KR',
    alphabet: [
      { letter: 'ㄱ', name: 'Giyeok', sound: 'g/k', example: '가다 gada (aller)'  },
      { letter: 'ㄴ', name: 'Nieun',  sound: 'n',    example: '나 na (moi)'        },
      { letter: 'ㄷ', name: 'Digeut', sound: 'd/t',  example: '달 dal (lune)'      },
      { letter: 'ㄹ', name: 'Rieul',  sound: 'r/l',  example: '라면 ramyeon'       },
      { letter: 'ㅁ', name: 'Mieum',  sound: 'm',    example: '머리 meori (tête)'  },
      { letter: 'ㅂ', name: 'Bieup',  sound: 'b/p',  example: '바다 bada (mer)'    },
      { letter: 'ㅅ', name: 'Siot',   sound: 's',    example: '사랑 sarang (amour)'},
      { letter: 'ㅇ', name: 'Ieung',  sound: 'ŋ/-',  example: '아 a (ah)'          },
      { letter: 'ㅈ', name: 'Jieut',  sound: 'dʒ',   example: '저 jeo (je, poli)' },
      { letter: 'ㅊ', name: 'Chieut', sound: 'tʃ',   example: '차 cha (thé)'       },
      { letter: 'ㅋ', name: 'Kieuk',  sound: 'k',    example: '코 ko (nez)'        },
      { letter: 'ㅌ', name: 'Tieut',  sound: 't',    example: '타다 tada (monter)' },
      { letter: 'ㅍ', name: 'Pieup',  sound: 'p',    example: '파 pa (vert/feuille)'},
      { letter: 'ㅎ', name: 'Hieut',  sound: 'h',    example: '하다 hada (faire)'  },
      { letter: 'ㅏ', name: 'A',      sound: 'a',    example: '아버지 abeoji (père)'},
      { letter: 'ㅓ', name: 'Eo',     sound: 'ʌ',    example: '어머니 eomeoni (mère)'},
      { letter: 'ㅗ', name: 'O',      sound: 'o',    example: '오다 oda (venir)'   },
      { letter: 'ㅜ', name: 'U',      sound: 'u',    example: '우리 uri (nous)'    },
      { letter: 'ㅡ', name: 'Eu',     sound: 'ɯ',    example: '으로 euro (vers)'   },
      { letter: 'ㅣ', name: 'I',      sound: 'i',    example: '이름 ireum (prénom)'},
    ],
    categories: COMMON_CATEGORIES,
    greetingWord: '안녕하세요!',
    familiarName: 'Coréen',
    difficulty: 'medium',
    aiSeedPrompt: `Tu es un professeur de coréen bienveillant. Toujours donner: hangeul, romanisation (Revised Romanization) et traduction française. Distinguer les niveaux de politesse (banmal/jondaemal).`,
  },
];

export function getLanguageByCode(code: string): LanguageConfig | undefined {
  return SUPPORTED_LANGUAGES.find(l => l.code === code);
}

export const DEFAULT_LANGUAGE_CODE = 'ar';